export interface AgentPreset {
  id: string
  name: string
  description: string
  marketFocus: '1x2' | 'asian_handicap' | 'over_under' | 'multi_market'
  decisionStyle: 'anticipatory' | 'confirmatory' | 'balanced' | 'volatility_breakout'
  aggressionType: 'instant' | 'confirmation' | 'cooldown'
  confirmationTolerance: 'aggressive' | 'conservative' | 'adaptive'
  phaseWeighting: 'early' | 'pre_halftime' | 'second_half' | 'late_stoppage' | 'full_match'
  sideBias: 'home' | 'away' | 'favorite' | 'underdog' | 'none'
  positionSizing: 'fixed' | 'percentage' | 'confidence_weighted'
  reactionLatencyMs: number
  contextVenueAware: boolean
  contextWeatherAware: boolean
  wildcardTrait: string
  volatilityWindow?: number
  breakoutZscore?: number
}

export const AGENT_PRESETS: AgentPreset[] = [
  {
    id: 'anticipatory-early-trader',
    name: 'Anticipatory Early Trader',
    description: 'Fires on high-danger possessions before goals - capitalizes on pre-event movements',
    marketFocus: '1x2',
    decisionStyle: 'anticipatory',
    aggressionType: 'instant',
    confirmationTolerance: 'aggressive',
    phaseWeighting: 'early',
    sideBias: 'none',
    positionSizing: 'fixed',
    reactionLatencyMs: 1000,
    contextVenueAware: false,
    contextWeatherAware: false,
    wildcardTrait: 'none',
  },
  {
    id: 'confirmatory-event-tracker',
    name: 'Confirmatory Event Tracker',
    description: 'Only trades on confirmed goals or official VAR outcomes - prioritizes safety',
    marketFocus: '1x2',
    decisionStyle: 'confirmatory',
    aggressionType: 'confirmation',
    confirmationTolerance: 'conservative',
    phaseWeighting: 'full_match',
    sideBias: 'none',
    positionSizing: 'percentage',
    reactionLatencyMs: 2000,
    contextVenueAware: false,
    contextWeatherAware: false,
    wildcardTrait: 'none',
  },
  {
    id: 'balanced-score-state',
    name: 'Balanced Score-State Trader',
    description: 'Blends anticipatory and confirmatory signals with score-state bias',
    marketFocus: '1x2',
    decisionStyle: 'balanced',
    aggressionType: 'cooldown',
    confirmationTolerance: 'adaptive',
    phaseWeighting: 'second_half',
    sideBias: 'none',
    positionSizing: 'confidence_weighted',
    reactionLatencyMs: 1500,
    contextVenueAware: true,
    contextWeatherAware: false,
    wildcardTrait: 'none',
  },
  {
    id: 'asian-handicap-specialist',
    name: 'Asian Handicap Specialist',
    description: 'Focuses on Asian Handicap markets with tight line band preferences',
    marketFocus: 'asian_handicap',
    decisionStyle: 'balanced',
    aggressionType: 'confirmation',
    confirmationTolerance: 'conservative',
    phaseWeighting: 'pre_halftime',
    sideBias: 'none',
    positionSizing: 'percentage',
    reactionLatencyMs: 2000,
    contextVenueAware: true,
    contextWeatherAware: true,
    wildcardTrait: 'none',
  },
  {
    id: 'over-under-momentum',
    name: 'Over/Under Momentum Trader',
    description: 'Tracks possession momentum and shooting patterns for Over/Under opportunities',
    marketFocus: 'over_under',
    decisionStyle: 'anticipatory',
    aggressionType: 'instant',
    confirmationTolerance: 'aggressive',
    phaseWeighting: 'late_stoppage',
    sideBias: 'none',
    positionSizing: 'fixed',
    reactionLatencyMs: 1500,
    contextVenueAware: false,
    contextWeatherAware: true,
    wildcardTrait: 'none',
  },
  {
    id: 'comeback-romantic',
    name: 'Comeback Romantic',
    description: 'Favors underdog teams with comeback wildcard trait - emotional betting style',
    marketFocus: '1x2',
    decisionStyle: 'anticipatory',
    aggressionType: 'cooldown',
    confirmationTolerance: 'adaptive',
    phaseWeighting: 'second_half',
    sideBias: 'underdog',
    positionSizing: 'confidence_weighted',
    reactionLatencyMs: 3000,
    contextVenueAware: false,
    contextWeatherAware: false,
    wildcardTrait: 'comeback_romantic',
  },
  {
    id: 'revenge-trader',
    name: 'Revenge Trader',
    description: 'Reverses losing trades with the revenge trader wildcard - responds to losses',
    marketFocus: '1x2',
    decisionStyle: 'balanced',
    aggressionType: 'instant',
    confirmationTolerance: 'aggressive',
    phaseWeighting: 'full_match',
    sideBias: 'none',
    positionSizing: 'fixed',
    reactionLatencyMs: 1000,
    contextVenueAware: false,
    contextWeatherAware: false,
    wildcardTrait: 'revenge_trader',
  },
  {
    id: 'contrarian-specialist',
    name: 'Contrarian Specialist',
    description: 'Takes opposite positions to consensus - thrives in unexpected situations',
    marketFocus: 'multi_market',
    decisionStyle: 'confirmatory',
    aggressionType: 'confirmation',
    confirmationTolerance: 'conservative',
    phaseWeighting: 'early',
    sideBias: 'none',
    positionSizing: 'percentage',
    reactionLatencyMs: 2500,
    contextVenueAware: true,
    contextWeatherAware: true,
    wildcardTrait: 'contrarian',
  },
  {
    id: 'last-minute-believer',
    name: 'Last Minute Believer',
    description: 'Only activates in final 15 minutes with high-conviction trades',
    marketFocus: '1x2',
    decisionStyle: 'anticipatory',
    aggressionType: 'instant',
    confirmationTolerance: 'aggressive',
    phaseWeighting: 'late_stoppage',
    sideBias: 'none',
    positionSizing: 'fixed',
    reactionLatencyMs: 500,
    contextVenueAware: false,
    contextWeatherAware: false,
    wildcardTrait: 'last_minute_believer',
  },
  {
    id: 'weather-prophet',
    name: 'Weather Prophet',
    description: 'Weather-aware trading focusing on adverse conditions affecting play',
    marketFocus: 'over_under',
    decisionStyle: 'balanced',
    aggressionType: 'confirmation',
    confirmationTolerance: 'conservative',
    phaseWeighting: 'full_match',
    sideBias: 'none',
    positionSizing: 'confidence_weighted',
    reactionLatencyMs: 2000,
    contextVenueAware: true,
    contextWeatherAware: true,
    wildcardTrait: 'weather_prophet',
  },
  {
    id: 'volatility-breakout-trader',
    name: 'Volatility Breakout Trader',
    description: 'Detects statistical outliers in odds movements using z-score analysis - pure quantitative approach',
    marketFocus: '1x2',
    decisionStyle: 'volatility_breakout',
    aggressionType: 'instant',
    confirmationTolerance: 'aggressive',
    phaseWeighting: 'full_match',
    sideBias: 'none',
    positionSizing: 'confidence_weighted',
    reactionLatencyMs: 1000,
    contextVenueAware: false,
    contextWeatherAware: false,
    wildcardTrait: 'none',
    volatilityWindow: 6,
    breakoutZscore: 1.5,
  },
]
